[feat] 逐字歌词使用 Win2D 实现
HyPlayer/HyPlayer pull request #418
Opened 2023-07-08 07:24 UTC by kengwang

2023-07-09 13:23 UTC, kengwang commented
[0001-feat-obsolete-Win2D-Composition.patch](https://github.com/HyPlayer/HyPlayer/files/11995243/0001-feat-obsolete-Win2D-Composition.patch)

使用 Win2D 套上 Composition 绘制歌词列表

2023-07-10 13:02 UTC, kengwang commented
@Clrs17 TNX, 这个分支没有那个歌单 Item 的异常修复, 每次调试都很烦. 但一直没把 develop merge 进来 /笑哭

2023-07-16 04:39 UTC, kengwang commented
我创建的 Pr，似乎不能自己给自己review

2023-07-16 05:12 UTC, Clrs17 commented
> 我创建的 Pr，似乎不能自己给自己review

我merge了一下，你现在可以了
只是最后一个提交者不可以

2023-07-16 07:36 UTC, zxbmmmmmmmmm requested changes
有个问题，切歌的时候小窗歌词可能不会更新....

2023-07-17 10:12 UTC, zxbmmmmmmmmm approved these changes

2023-07-17 11:36 UTC, merged